### ISSUE TITLE
Roadmap to 1.0 release

### ISSUE THREAD

**Issue by smichaelsen** [sinso/typo3-webcomponents#55]
- [ ] Fix phpstan pipeline
- [ ] Add unit tests
- [ ] Dispatch `ComponentWillBeRendered` event when rendering via `ComponentRenderingHelper`
- [ ] Collect and integrate feedback on DX
